from pendulum import datetime, duration

#DEFAULT ARGUMENTS
DEFAULT_OWNER = "Airflow"
DEFAULT_RETRIES = 10
DEFAULT_RETRY_DELAY = duration(minutes=15)
DEFAULT_RETRY_EXPONENTIAL_BACKOFF = True
DEFAULT_MAX_RETRY_DELAY = duration(hours=12)

#MYSQL TASK ARGUMENT
MYSQL_RETRIES = 20
MYSQL_RETRY_DELAY = duration(minutes=1)

#DOCKER TASK ARGUMENT
DOCKER_RETRIES = 2
DOCKER_RETRY_DELAY = duration(minutes=30)

#GIT REST API TASK ARGUMENT
GIT_REST_API_RETRIES = 100
GIT_REST_API_RETRY_DELAY = duration(minutes=15)
GIT_REST_API_MAX_RETRY_DELAY = duration(hours=24)