from pendulum import duration

#DEFAULT ARGUMENTS
DEFAULT_OWNER = "Airflow"
DEFAULT_RETRIES = 5
DEFAULT_RETRY_DELAY = duration(minutes=2)
DEFAULT_RETRY_EXPONENTIAL_BACKOFF = False
DEFAULT_MAX_RETRY_DELAY = duration(hours=1)

#SETTINGS TASK ARGUMENT
SETTINGS_RETRIES = 10
SETTINGS_RETRY_DELAY = duration(hours=12)

#MYSQL TASK ARGUMENT
MYSQL_RETRIES = 10
MYSQL_RETRY_DELAY = duration(minutes=2)

#DOCKER TASK ARGUMENT
DOCKER_RETRIES = 2
DOCKER_RETRY_DELAY = duration(minutes=5)

#GIT REST API TASK ARGUMENT
GIT_REST_API_RETRIES = 10
GIT_REST_API_RETRY_DELAY = duration(minutes=5)

#FILE MANAGER TASK ARGUMENT
FILE_MANAGER_RETRIES = 10
FILE_MANAGER_RETRY_DELAY = duration(minutes=5)
